# Generated by Django 3.2.8 on 2021-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_child_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
